### ISSUE TITLE
Resize tiles for better layout on github

### ISSUE THREAD

**Issue by dylemma** [ozh/github-colors#14]
The 150x150 images leave some dead space on the side of the layout

![image](https://user-images.githubusercontent.com/1355958/31297476-187fadb8-aab4-11e7-88a2-ce6d28120104.png)

The layout has 888px available, so if you use 148x148 tiles, you could fit 6 tiles per row with zero leftover&nbsp;space.

![image](https://user-images.githubusercontent.com/1355958/31297453-07a7f130-aab4-11e7-8151-f18ed5ea7f1b.png)

**Comment by ozh** [comment]
Sure, why not. PR welcome.
