### ISSUE TITLE
HTML is not a programming language

### ISSUE THREAD

**Issue by Xeverous** [ozh/github-colors#23]
As far as GitHub and it's repositories are concerned, it allows to host many non-programming languages including HTML, TeX and many others.

This issue aims to correct the baner "GitHub programming language colors" to "GitHub language colors". As programmers, we should pay attention to the details.

**Comment by ozh** [comment]
Absolutely. PR? :)

**Comment by Xeverous** [comment]
Do you really need a PR for this? Just change the string.

**Comment by ozh** [comment]
Change the string in the py script then run it to update the json and the readme then commit the result, which I can't do on my mobile, hence asking

**Comment by Alhadis** [comment]
It isn't? So *THAT'S* why my programs won't start…

I've been building robots out of `<MARQUEE>` tags for the last 20 years, why didn't anyone tell me sooner…?! 😢  😭
