### ISSUE TITLE
Images aren't loading

### ISSUE THREAD

**Issue by pxeger** [ozh/github-colors#45]
This is pretty clearly not a problem with this repo, but with GitHub and/or placeholder.com - I'm not sure which, but I thought I'd open an issue to mention it anyway,

In the README, most of the images don't load. This seems to be an issue related to GitHub's image proxying (`camo.githubusercontent.com`) - it returns HTTP 502, quoting an upstream HTTP 403. I can load the images fine if I copy the raw URL (e.g. `http://via.placeholder.com/148x148/814CCC/ffffff&text=1C%20Enterprise`)

**Comment by ozh** [comment]
Hey,

Thanks for the heads up. I've tried another image placeholder service, it seems to work. When it fails maybe it will be time to use an in-house placeholder system :)
