### ISSUE TITLE
Change in Structure of the color.json

### ISSUE THREAD

**Issue by RamolaWeb** [ozh/github-colors#8]
It will be great to change the structure of the color.json because till now it contains the a large number of the JSON Object in a single JSON Object . We should be changing  the structure so that it contains a JSON Array of the JSON Objects as all the Objects provided in the file  have same characteristics. Thus the JSON Object will easily serialize into JAVA objects by the Library Like GSON and Jackson.

**Comment by RamolaWeb** [comment]
I would like to  create a list to add all the objects and in the loop at the line 68 of script I will add the OrderedDict to the list and then dumps that list to the JSON.

**Comment by ozh** [comment]
I'm not getting back to Python anytime soon. Feel free to submit a pull request, with an example of the JSON array before and after, I'm very OK to merge any sensible code proposal.
